# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60cdff3c8c81f490f973f97203f02b9b3766941b6e93098980b6b24858e368d35b958ce6a81a6705ce8d97e180ef7bebf791a403f950a587ee27237ffd410e01

test:
  secret_key_base: 8ea054f11d6bf87f3b673563788a0ebf43c7543c0f021edb3fdb9fd77837a8673092fb6ac9cc951229f001b3ed8e96cb67cb2308d0a8f9002f8deee8e2d4b1e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
